# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= atmel-dfu
LAYOUTS ?= 60_ansi 60_ansi_arrow_split_bs_7u_spc 60_ansi_arrow 60_ansi_split_bs_rshift 60_hhkb 60_iso 60_abnt2 60_tsangan_hhkb
MCU ?= atmega32u4
MOUSEKEY_ENABLE ?= on
BOOTMAGIC_ENABLE ?= yes
MOUSEKEY_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= no
COMMAND_ENABLE ?= no
NKRO_ENABLE ?= yes
BACKLIGHT_ENABLE ?= yes
RGBLIGHT_ENABLE ?= yes
AUDIO_ENABLE ?= no
